### ISSUE TITLE
Crashes On Launch

### ISSUE THREAD

**Issue by SCBionicle** [malware-dev/MDK-Debug#1]
`2020-08-09 17:17:42.906 - Thread:   1 ->  Exception occured: System.MissingMethodException: Method not found: 'Void Sandbox.Game.Gui.MyTerminalControlButton`1..ctor(System.String, VRage.Utils.MyStringId, VRage.Utils.MyStringId, System.Action`1<!0>)'.
   at MDK.Debug.ProgrammableBlockExtensions.Install()
   at MDK.Debug.Plugin.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)`

**Comment by malware-dev** [comment]
Noted, thank you

**Comment by 0xCCF4** [comment]
I had the same issue. After a local recompile it works fine again.

**Comment by malware-dev** [comment]
Ah, alright, good to know, then I'd probably not have gotten the error myself as I'd need to rebuild. Probably just need a reimaging then. @SCBionicle Please confirm @MyJojoX's findings, then I can close/pin this issue.

**Comment by SCBionicle** [comment]
Sorry, just got the email now. Yeah, I'll check in the morning. It shouldn't be difficult to install the necessary tools. Is there any build tool dependencies I need to be aware of?

**Comment by malware-dev** [comment]
I apologize. I assumed you already had done so, I'd forgotten that I'd made a release package. Which means I need to do so again! 😄 

No dependencies I can think of. The only thing you need to do is edit `SpaceEngineersPath.props` to match your own folder structure.

**Comment by malware-dev** [comment]
Rebuild release made.

**Comment by SCBionicle** [comment]
Ah, that's probably the reason why it crashed. My SE directory is in a nontypical location.

**Comment by SCBionicle** [comment]
Yeah, I'll recompile it when I get the chance. Sorry, bit busy today.
